### ISSUE TITLE
Mouse wheel gestures do not work on tabs which have not finished loading

### ISSUE THREAD

**Issue by IgorKrupenja** [ys0115/OperaGestures#1]
macOS 10.13.6
Firefox 61.0.1

1. Install OperaGestures plugin and make sure that mouse wheel gestures are enabled.
2. Open several tabs in Firefox.
3. Try using mouse wheel gestures before tabs finish loading.

Changing tabs works but only for tabs which have finished loading. If you switch to a tab which has not yet finished loading, mouse wheel gestures stop working until that tab finishes loading.

Btw, thank you for this add-on: even with this bug, it is still the best solution for mouse wheel scrolling on macOS. I gave you 5 stars on AOM ;)

**Comment by ys-j** [comment]
@krupenja Thank you for using and rating!  And I'm sorry for your inconvenience.
I'd just updated this addon.  Let me know if you find any bugs.
Thanks!

**Comment by IgorKrupenja** [comment]
With the new version I do not think this is reproducible anymore. Closing.
