### ISSUE TITLE
Chrome version?

### ISSUE THREAD

**Issue by IgorKrupenja** [ys0115/OperaGestures#2]
I was wondering if it would be possible to also have a Chrome version of the plugin? Right now I do not know of any Chrome plugins where mouse gestures are implemented well on macOS.

**Comment by ys-j** [comment]
@krupenja I'm sorry, I cannot publish Chrome version to Chrome Web Store:

1. I don't have Mac devices, so I can't make sure if this addon works well on Mac OS
2. It costs $5, but I don't want to pay :p 

Instead I uploaded source codes (/src-chrome), please download and try to install, refering to [this video](https://www.youtube.com/watch?v=IP0nMv_NI1s&t=20s).
Thanks!
