### ISSUE TITLE
Contex menu opens when doing a right click for gestures 

### ISSUE THREAD

**Issue by hartkopp** [ys0115/OperaGestures#4]
Hi,
I'm using a Firefox 60.3esr and added your addon as my former addon FireGestures did not work on FF60 anymore. The addon works but when I press the right mouse button to start the gesture the context menu pop-up emerges at the same time and doesn't close after the gesture (e.g. back) was performed.
I doublechecked with an older FF version and Firegestures: With that setup the context menu emerges after some delay - but not when a gesture is performed.
Any idea?

**Comment by ys-j** [comment]
@hartkopp Thank you for using this add-on. Do you perhaps use Mac or Linux? If so, please try to open **about:config** and change "ui.context_menus.after_mouseup" value to ***true***. Hope that helps. Thanks!

**Comment by hartkopp** [comment]
Yes, indeed I'm using Linux. And after setting the suggested config option, everything works as expected! Great job! Maybe you can test for Mac/Linux in your add-on and modify this option on your own. Or is this not wanted by Mozilla guidelines to modify this kind of settings?
Thanks,
Oliver

**Comment by ys-j** [comment]
@hartkopp Unfortunately, we can't modify any config options by add-on due to WebExtensions restriction. So, I added an explanation to AMO page. Thank you for your kind suggestion.

**Comment by ys-j** [comment]
Updated new version v0.7b4: Now available new option to modify browser settings with additional permission.

**Comment by hartkopp** [comment]
Excellent! Thank you for integrating this feature for Linux/Mac users.
