### ISSUE TITLE
Sites with Framesets have wrong height

### ISSUE THREAD

**Issue by mamoep** [ys0115/OperaGestures#5]
When I browse sites with framesets, the height gets cut to approx. 300px. Makes the content almost unreadable. When I disable the extension, the issue is gone.

Version 0.7b5
Firefox 60.4.0 ESR

Example screenshot
![screenshot-2019-1-23 unified manager 9 5 documentation center](https://user-images.githubusercontent.com/26142342/51611921-a63de700-1f20-11e9-9067-7e3fd0e7781d.png)

**Comment by ys-j** [comment]
@mamoep I'm sorry for your inconvenience and thank you for your report.  I fixed this bug on recent version 0.7b6, please update the extension!  Thanks.

**Comment by mamoep** [comment]
Thank you!
