### ISSUE TITLE
Context menu on mapy.cz

### ISSUE THREAD

**Issue by Alfoxxx** [ys0115/OperaGestures#7]
How to fix the display of the right click context menu on mapy.cz? When the extension is turned on, the context menu is not displayed.

When the extension is turned off, the context menu is displayed ok:
![Capture1626](https://user-images.githubusercontent.com/44336284/85941979-9ea91b80-b926-11ea-9e37-96dfe59ab708.jpg)

**Comment by ys-j** [comment]
@Alfoxxx Sorry for your inconvenience. I fixed it in version v0.7b7. Thank you for your support.
