### ISSUE TITLE
Beta feature (Draw pointer)

### ISSUE THREAD

**Issue by gitbees165** [ys0115/OperaGestures#8]
I tested the Draw pointer option but it doesn't seem to work. I could share the debug logs if you need it. BTW this is very nice (36KB) and thanks for the extension. The other mouse gesture addons with draw line option are all ~600/900KB size.

**Comment by ys-j** [comment]
@spacedingo Thank you for your report and compliment. I fixed in version 0.7b9, please update and check it.

**Comment by gitbees165** [comment]
@ys-j Quickly tested draw line and it's working as expected back/front. Will test it more and report if anything. Thanks!
